### ISSUE TITLE
Move to OWASP

### ISSUE THREAD

**Issue by Padi-owasp** [The-OAG-Development-Project/Application-Gateway#44]
- [x] Move Repo to OAG specific organization
- [x] Make sure Snyk and Codacy work with the new repo name
- [x] Move Docker images to the OWASP docker hub account (Get access and update CI)
- [x] Rename to packages org.owasp.oagw (owg=owasp application gateway) or similar.
- [x] Update Banner Image
- [x] Update terminology on wiki
- [x] Update terminology in code

**Comment by Padi-owasp** [comment]
Attention! Do not do this while other Dev's have topics open!
Else you create a merge hell!

**Comment by gianlucafrei** [comment]
That's true. 👍 Let's coordinate on this.
